### ISSUE TITLE
How trained_models/ours.pth.tar are generated?

### ISSUE THREAD

**Issue by ghost** [laoreja/HPLFlowNet#1]
Hi,

Thanks for outsourcing the code for the commendable work done.

When i started executing python3 main.py configs/test_ours_KITTI.yaml, it uses trained_models/ours.pth.tar. 
If i want to retain from scratch for new dataset, how to generate this trained_models/ours.pth.tar file?
Kindly suggest how to go ahead.

**Comment by laoreja** [comment]
Use the train ours configure file
