### ISSUE TITLE
the complexity of point interpolate using permutohedral lattice vs  integer lattice

### ISSUE THREAD

**Issue by tornadomeet** [laoreja/HPLFlowNet#15]
hello, @laoreja 

in your paper, it said that the complexity of point interpolate using integer lattice is ```2^d```, if using permutohedral lattice, then the complexity is ```d^2```.

but if we only use point cloud during scene flow estimation, so ```d=3```, the complexity of permutohedral lattice(3^2=9) is large than  that of integer lattice(2^3=8).  is it correctly? thanks.

**Comment by laoreja** [comment]
I think it's correct. Though bigO notation will have some constant factors etc. When d=3, may be permutohedral lattice will have less advantage. It will be more useful for higher dimensional space, e.g., include RGB features in the space.

**Comment by tornadomeet** [comment]
thanks!
