### ISSUE TITLE
tar error with the trained_models ours.pth.tar

### ISSUE THREAD

**Issue by 008yheng** [laoreja/HPLFlowNet#17]
when extract model file from ours.pth.tar ,there is a error
tar -xvf ours.pth.tar
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors

**Comment by laoreja** [comment]
I used torch load to directly load this file. Never tried unzipping  it.

**Comment by 008yheng** [comment]
thanks

**Comment by 008yheng** [comment]
i'm new to this field,i find the point cloud which as  input for the net is generate by stereo matching,can i take piont cloud by lidar as the input ? what need to pay attention?

**Comment by laoreja** [comment]
Hi, I haven’t tried that because I have no lidar data with ground truth. Basically it should be fine.
