### ISSUE TITLE
Values of all_epe3d = np.load(osp.join(visu_path, 'epe3d_per_frame.npy')) are Inf?

### ISSUE THREAD

**Issue by ghost** [laoreja/HPLFlowNet#2]
After performing python3.5 main.py configs/test_ours_KITTI.yaml with your  pretrained model,
and then python3.5 checkpoints/test/ours_KITTI_8192_35m/visu_ours_KITTI_8192_35m
the values of all_epe3d  are Inf and mayavi results shows completely black.
Kindly help

Test: [1/142]	EPE3D inf (inf)	ACC3DS 0.0000 (0.0000)	ACC3DR 0.0000 (0.0000)	Outliers3D 1.0000 (1.0000)	EPE2D 2968.2300 (2968.2300)	ACC2D 0.0000 (0.0000)
Test: [51/142]	EPE3D inf (inf)	ACC3DS 0.0000 (0.0000)	ACC3DR 0.0000 (0.0000)	Outliers3D 1.0000 (1.0000)	EPE2D 3677.0613 (8794.5203)	ACC2D 0.0000 (0.0000)
Test: [101/142]	EPE3D 29747781010718720.0000 (inf)	ACC3DS 0.0000 (0.0000)	ACC3DR 0.0000 (0.0000)	Outliers3D 1.0000 (1.0000)	EPE2D 15020.6162 (10022.9352)	ACC2D 0.0000 (0.0000)
 * EPE3D inf	ACC3DS 0.0000	ACC3DR 0.0000	Outliers3D 1.0000	EPE2D 9208.8389	ACC2D 0.0000

**Comment by laoreja** [comment]
One possible reason is pytorch changed some APIs, so please use the pytorch version specified in the readme

**Comment by ghost** [comment]
Thanks ...closing the issue

**Comment by tornadomeet** [comment]
```conda install pytorch=0.4.1 cuda90 -c pytorch``` solved this problem.
