### ISSUE TITLE
the range of output_0.npy using trained_models/ours.pth.tar is between minrange and maxrange values e+10 and e-10

### ISSUE THREAD

**Issue by ghost** [laoreja/HPLFlowNet#3]
After performing python3.5 main.py configs/test_ours_KITTI.yaml with your pretrained model,
the checkpoint directories are created with 
epe3d_per_frame.npy
output_0.npy
pc1_0.npy
pc2_0.npy
sample_path_list.pickle
sf_0.npy.

The range of output_0.npy is between e-10 and e-13. 
python3 visualization.py VISU_DIR display nothing because of larger values of output_0.npy which is between e-10 and e+13. 

Kindly help us

**Comment by ghost** [comment]
@laoreja , can you kindly help me

**Comment by laoreja** [comment]
Same issue as previous one. Also make sure you run the preprocess code correctly and try to visualize them
