### ISSUE TITLE
How to encode motion field from large motion to smaller motion?Static Vs Dynamic

### ISSUE THREAD

**Issue by ghost** [laoreja/HPLFlowNet#5]
I visualized the optical flow results. Looks convincing and i got speed at 49-53ms on an average using 2080Ti which is quite convincing. In order to distinguish static/moving object which section of the code needs to be modified. Pls help

**Comment by ghost** [comment]
@laoreja , can you kindly help me

**Comment by laoreja** [comment]
We never worked on motion segmentation -- it's is not mentioned in our paper. For the figure, I simply used some mayavi APIs to pot the motion segment with a colormap, and the color relates to the magnitude/velocity. Thanks!
