### ISSUE TITLE
The training speed is very slow

### ISSUE THREAD

**Issue by pxiangwu** [laoreja/HPLFlowNet#6]
Hi, I just found that the training speed is very slow. I wonder if there is any problem with my configuration? I used Pytorch0.4.0 and cuda 9.0, on a single RTX Titan. 

How long did it take to train the model for 800 epochs?

Thank you so much.

**Comment by laoreja** [comment]
Yes, the training is slow. 
Some CUDNN optimization doesn’t work for varying input size. 
My model is trained for about 500~600 epochs. I didn’t remember the exact training time, roughly several days.
