### ISSUE TITLE
Scale filter map for the shallow model

### ISSUE THREAD

**Issue by hehefan** [laoreja/HPLFlowNet#8]
Hi, what is the scale filter map for the shallow model?

**Comment by laoreja** [comment]
It should be

scales_filter_map: [[4., 1, -1, -1],
                    [2., 1, -1, -1],
                    [1., 1, 1, 1],
                    [0.5, 1, 1, 1],
                    [0.25, 1, 1, 1]]

However, since I no longer have access to TuSimple machines, I don't have the learning rate scheme and the trained model. Remember to multiply learning rate by 0.7 and gradually decrease it.

**Comment by hehefan** [comment]
Many thanks.
